# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcribe.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10transcribe.proto\"i\n\x10\x44iarizationEntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07speaker\x18\x02 \x01(\t\x12\r\n\x05start\x18\x03 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x02\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x0e\n\x06gender\x18\x06 \x01(\t\"&\n\x11TranscribeRequest\x12\x11\n\taudio_url\x18\x01 \x01(\t\"a\n\x12TranscribeResponse\x12&\n\x0b\x64iarization\x18\x03 \x03(\x0b\x32\x11.DiarizationEntry\x12\x11\n\taudio_url\x18\x04 \x01(\t\x12\x10\n\x08speakers\x18\x05 \x03(\t2O\n\x11TranscribeService\x12:\n\x0fTranscribeAudio\x12\x12.TranscribeRequest\x1a\x13.TranscribeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcribe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIARIZATIONENTRY']._serialized_start=20
  _globals['_DIARIZATIONENTRY']._serialized_end=125
  _globals['_TRANSCRIBEREQUEST']._serialized_start=127
  _globals['_TRANSCRIBEREQUEST']._serialized_end=165
  _globals['_TRANSCRIBERESPONSE']._serialized_start=167
  _globals['_TRANSCRIBERESPONSE']._serialized_end=264
  _globals['_TRANSCRIBESERVICE']._serialized_start=266
  _globals['_TRANSCRIBESERVICE']._serialized_end=345
# @@protoc_insertion_point(module_scope)
